"""Public voice API for OSA 0.7.x."""

from osa.voice.activation import (
    AlwaysActiveVoiceActivationDetector,
    KeywordVoiceActivationDetector,
    VoiceActivationDetector,
    VoiceActivationError,
    VoiceActivationResult,
    create_always_active_detector,
    create_keyword_activation_detector,
)
from osa.voice.audio import (
    AudioInputError,
    AudioOutputError,
    FakeMicrophone,
    FakeSpeaker,
    MicrophoneInput,
    SpeakerOutput,
    create_fake_microphone,
    create_fake_speaker,
)
from osa.voice.barge_in import (
    BargeInConfig,
    BargeInError,
    BargeInState,
    VoiceBargeInMonitor,
    create_barge_in_monitor,
)
from osa.voice.composition import (
    VoiceCompositionError,
    create_default_voice_runtime,
    create_voice_runtime_from_backend,
)
from osa.voice.contracts import (
    VoiceContractError,
    VoiceInput,
    VoiceOutput,
    VoiceSessionConfig,
    VoiceSessionState,
    VoiceTranscript,
)
from osa.voice.faster_whisper_stt import (
    FasterWhisperConfig,
    FasterWhisperSpeechToText,
    create_faster_whisper_stt,
)
from osa.voice.normalization import (
    AudioNormalizationConfig,
    AudioNormalizationError,
    NormalizedAudio,
    VoiceAudioNormalizer,
    create_voice_audio_normalizer,
)
from osa.voice.piper_tts import (
    PiperTTSConfig,
    PiperTextToSpeech,
    create_piper_tts,
)
from osa.voice.platform import (
    AudioBackend,
    AudioPlatform,
    AudioPlatformError,
    AudioPlatformUnavailableError,
    DesktopAudioBackendFactory,
    UnavailableAudioBackend,
    create_audio_backend_factory,
    create_default_audio_backend,
)
from osa.voice.providers import (
    VoiceProviderConfig,
    VoiceProviderConfigError,
    VoiceProviderSelection,
    create_default_voice_provider_config,
    load_voice_provider_config,
)
from osa.voice.runtime import (
    VoiceRuntime,
    VoiceRuntimeConfig,
    VoiceRuntimeError,
    VoiceRuntimeState,
    create_voice_runtime,
)
from osa.voice.session import (
    VoiceAgent,
    VoiceSession,
    VoiceSessionError,
    VoiceSessionResult,
    VoiceSessionStateError,
)
from osa.voice.stt import (
    FixedSpeechToText,
    SpeechToText,
    SpeechToTextError,
)
from osa.voice.streaming import (
    BufferedSpeechToTextStream,
    ChunkedTextToSpeechStream,
    StreamingSpeechToText,
    StreamingTextToSpeech,
    VoiceStreamChunk,
    VoiceStreamingError,
    VoiceStreamingState,
    create_buffered_stt_stream,
    create_chunked_tts_stream,
)
from osa.voice.tts import (
    FixedTextToSpeech,
    TextToSpeech,
    TextToSpeechError,
)
from osa.voice.vad import (
    EnergyVoiceActivityDetector,
    VoiceActivityDetectionError,
    VoiceActivityDetector,
)

__all__ = [
    "AlwaysActiveVoiceActivationDetector",
    "AudioBackend",
    "AudioInputError",
    "AudioNormalizationConfig",
    "AudioNormalizationError",
    "AudioOutputError",
    "AudioPlatform",
    "AudioPlatformError",
    "AudioPlatformUnavailableError",
    "BargeInConfig",
    "BargeInError",
    "BargeInState",
    "BufferedSpeechToTextStream",
    "ChunkedTextToSpeechStream",
    "DesktopAudioBackendFactory",
    "EnergyVoiceActivityDetector",
    "FakeMicrophone",
    "FakeSpeaker",
    "FixedSpeechToText",
    "FixedTextToSpeech",
    "FasterWhisperConfig",
    "FasterWhisperSpeechToText",
    "KeywordVoiceActivationDetector",
    "MicrophoneInput",
    "NormalizedAudio",
    "PiperTTSConfig",
    "PiperTextToSpeech",
    "SpeakerOutput",
    "SpeechToText",
    "SpeechToTextError",
    "StreamingSpeechToText",
    "StreamingTextToSpeech",
    "TextToSpeech",
    "TextToSpeechError",
    "UnavailableAudioBackend",
    "VoiceActivationDetector",
    "VoiceActivationError",
    "VoiceActivationResult",
    "VoiceActivityDetectionError",
    "VoiceActivityDetector",
    "VoiceAgent",
    "VoiceAudioNormalizer",
    "VoiceBargeInMonitor",
    "VoiceCompositionError",
    "VoiceContractError",
    "VoiceInput",
    "VoiceOutput",
    "VoiceProviderConfig",
    "VoiceProviderConfigError",
    "VoiceProviderSelection",
    "VoiceRuntime",
    "VoiceRuntimeConfig",
    "VoiceRuntimeError",
    "VoiceRuntimeState",
    "VoiceSession",
    "VoiceSessionConfig",
    "VoiceSessionError",
    "VoiceSessionResult",
    "VoiceSessionState",
    "VoiceSessionStateError",
    "VoiceStreamChunk",
    "VoiceStreamingError",
    "VoiceStreamingState",
    "VoiceTranscript",
    "create_audio_backend_factory",
    "create_always_active_detector",
    "create_barge_in_monitor",
    "create_buffered_stt_stream",
    "create_chunked_tts_stream",
    "create_default_audio_backend",
    "create_default_voice_provider_config",
    "create_default_voice_runtime",
    "create_fake_microphone",
    "create_fake_speaker",
    "create_faster_whisper_stt",
    "create_keyword_activation_detector",
    "create_piper_tts",
    "create_voice_audio_normalizer",
    "create_voice_runtime",
    "create_voice_runtime_from_backend",
    "load_voice_provider_config",
]
